CREATE TABLE IF NOT EXISTS SensorLog (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    sensor VARCHAR(20) NOT NULL,
    description VARCHAR(30) NOT NULL,
    log_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);